---
title: Nota Bene Records
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  artists:
    title: Artists
    output: true
  partners:
    title: Partners
    output: true
  store:
    title: Store
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    title: Post Title
    permalink: /posts/:title
- scope:
    path: ''
    type: artists
  values:
    title: Artist Name
    description: A short description of the artist can go here
    image: ''
    cover_image: ''
    website: ''
    is_featured: false
    social_media:
      facebook: ''
      instagram: ''
      twitter: ''
    albums:
      - title: ''
        image: ''
        year: ''
        is_featured: false
    permalink: /artists/:title
    layout: artist-page
- scope:
    path: ''
    type: partners
  values:
    title: Company Name
    description: A short description of the company can go here
    image: ''
    cover_image: ''
    website: ''
    is_featured: false
    social_media:
      facebook: ''
      instagram: ''
      twitter: ''
    permalink: /partners/:title
    layout: partner-page
- scope:
    path: ''
    type: store
  values:
    title: Store Item Name
    description: A short description of the store item can go here
    image: ''
    price: ''
    link: ''
    permalink: /store/:title
    layout: store-page
sass:
    sass_dir: _sass
    style: compressed
description: Website description goes here
url: ''
email: contact@notabenerecords.com
color: '#333333'