name: Nota Bene Records
description: The website for Nota Bene Records
author: Nota Bene Records
url:

twitter:
color:

markdown: kramdown

collections:
  artists:
    output: true
    permalink: /artists/:path/
  partners:
    output: false
  store:
    output: true
    permalink: /store/:path/

defaults:
  - scope:
      type: artists
    values:
      layout: artist
  - scope:
      type: store
    values:
      layout: store